name: rigbi-env
channels:
  - defaults
dependencies:
  - affine
  - attrs
  - blas
  - bottleneck
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - ca-certificates
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - colorama
  - cryptography
  - curl
  - cycler
  - expat
  - fftw
  - fiona
  - fonttools
  - freetype
  - freexl
  - gdal
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - hdf4
  - hdf5
  - icc_rt
  - idna
  - intel-openmp
  - joblib
  - jpeg
  - kealib
  - kiwisolver
  - krb5
  - lerc
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcurl
  - libdeflate
  - libgdal
  - libiconv
  - libnetcdf
  - libpng
  - libpq
  - libspatialindex
  - libspatialite
  - libssh2
  - libtiff
  - libwebp
  - libwebp-base
  - libxml2
  - libzip
  - lz4-c
  - m2w64-expat
  - m2w64-gcc-libgfortran
  - m2w64-gcc-libs
  - m2w64-gcc-libs-core
  - m2w64-gettext
  - m2w64-gmp
  - m2w64-libiconv
  - m2w64-libwinpthread-git
  - m2w64-xz
  - mapclassify
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - msys2-conda-epoch
  - munch
  - munkres
  - networkx
  - numexpr
  - numpy
  - numpy-base
  - openjpeg
  - openssl
  - packaging
  - pandas
  - pillow
  - pip
  - proj
  - pycparser
  - pyopenssl
  - pyparsing
  - pyproj
  - pysocks
  - python
  - python-dateutil
  - pytz
  - rasterio
  - requests
  - rtree
  - scikit-learn
  - scipy
  - setuptools
  - shapely
  - six
  - snuggs
  - sqlite
  - threadpoolctl
  - tiledb
  - tk
  - tqdm
  - tzdata
  - urllib3
  - vc
  - vs2015_runtime
  - wheel
  - win_inet_pton
  - wincertstore
  - xerces-c
  - xz
  - zlib
  - zstd
